### ISSUE TITLE
Incorporate ChEMBL submission info into database

### ISSUE THREAD

**Issue by incoherentboy** [OpenSourceMalaria/OSM_compounds#3]
After 1st deposition to ChEBML (https://www.ebi.ac.uk/chembl/malaria), we will need to incorporate some way of tracking which compounds have been deposited and allow easy deposition of new compounds to ChEMBL in the format they require. I suspect the easiest way to do this is include a deposition .xls with linked values from the appropriate bioactivity fields in the main database?

**Comment by alintheopen** [comment]
Closing. Again related to Master Chemical List issues discussed in another thread.
